### ISSUE TITLE
microcmsプロジェクトのニュースにおけるカテゴリが必須項目になっていない

### ISSUE THREAD

**Issue by tacitusxo** [microcmsio/nextjs-simple-corporate-site-template#7]
便利なテンプレートを提供いただきありがとうございます。
[シンプルなコーポレートサイト](https://templates.microcms.io/templates/detail/d31fd55a-7a23-4b03-9c27-baa753ce75db)にて、`このテンプレートを使用する`で作成されたmicrocmsのプロジェクトでニュースのカテゴリが必須項目になっていないです。
そのためカテゴリを入力しなかった場合に、レンダリングに失敗します。

**Comment by shibe97** [comment]
@takikunxo 
ご連絡ありがとうございます！
#6 こちらのプルリクで解消されました！
